name: CD-lambda

on: 
    push:
        branches: ["main"]

jobs:
    prepare-lambda-function:
        runs-on: ubuntu-latest

        steps:
          - name: Copy code
            uses: actions/checkout@v4

            # CD - Delivery
          - name: prepare-file
            run: |
                cd lambda && zip -r ./lambda_function.zip .
                mv lambda_function.zip ../

          - name: Upload zip-artifact
            uses: actions/upload-artifact@v4
            with:
                name: lambda-package
                path: lambda_function.zip

